language: ruby
rvm:
  - ruby-2.1.1
  - rbx-2.2.6

before_script:
  - "yes | sudo apt-get install flex bison libqt4-dev gcc g++ git sloccount perl perl-modules"
  - "yes | sudo cpanp -i Class::Accessor Getopt::Euclid Graph List::Compare Statistics::Descriptive Statistics::OnLine Test::Class Test::Exception YAML"
  - "git clone git://gitorious.org/analizo/doxyparse.git"
  - "cd doxyparse"
  - "./configure --with-doxyparse"
  - "make"
  - "sudo install bin/doxyparse /usr/local/bin/"
  - "cd .."
  - "wget http://www.analizo.org/download/analizo_1.18.0.tar.gz"
  - "tar -xzvf analizo_1.18.0.tar.gz"
  - "cd analizo"
  - "perl Makefile.PL"
  - "make"
  - "sudo make install"
  - "cd .."
  - "cp config/database.yml.sample config/database.yml"
  - "bundle exec rake db:migrate RAILS_ENV=test"

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
